name: EmojiCore
main: cc.imcanada.emoji.Main
version: 1.0.2
author: imcanada.cc
commands:
   emojis:
      description: List of available emojis
      usage: /emojis
      permission: emojicore.emojis
      permission-message: You do not have permission to use this command.
   emojicore:
      description: Info about emojicore
      usage: /emojicore
      permission: emojicore.info
      permission-message: You do not have permission to use this command.
   emojireload:
      description: Reloads emojicore config
      usage: /emojireload
      permission: emojicore.reload
      permission-message: You do not have permission to use this command.